final testRawblockResponse = {
  'hash': '0000000000000000000b4d0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e',
  'ver': 1,
  'prev_block': '0000000000000000000a4d0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0',
  'mrkl_root': '4d0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e',
  'time': 1625097600,
  'bits': 403014710,
  'next_block': [
    '0000000000000000000c4d0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0',
  ],
  'fee': 5000,
  'nonce': 2083236893,
  'n_tx': 10,
  'size': 123456,
  'block_index': 1000000,
  'main_chain': true,
  'height': 680000,
  'weight': 4000000,
  'tx': [
    {
      'hash': '4e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0',
      'ver': 1,
      'vin_sz': 2,
      'vout_sz': 2,
      'size': 250,
      'weight': 1000,
      'fee': 5000,
      'relayed_by': '0.0.0.0',
      'lock_time': 0,
      'tx_index': 1,
      'double_spend': false,
      'time': 1625097600,
      'block_index': 1000000,
      'block_height': 680000,
      'inputs': [
        {
          'sequence': 4294967295,
          'witness': '',
          'script':
              '483045022100f3b7b153d5eab7317f6ea0b93f9573b6d3a1c6d6f6cf7f4f3105a7dbbbf5aa802202e59b8b499a64e5b8f4df2c23f27e5e30357a5a0e12c30b8c6e0d23427c014b30121034e8d6e89b4f70c37389fa5e1f1d8a28b8d687f6f9c3e4b0b48e4f4c2a7f0b3b2',
          'index': 0,
          'prev_out': {
            'type': 0,
            'spent': true,
            'value': 5000000000,
            'spending_outpoints': [
              {
                'tx_index': 1,
                'n': 0,
              }
            ],
            'n': 0,
            'tx_index': 1,
            'script': '76a91488ac',
            'addr': '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
          },
        }
      ],
      'out': [
        {
          'type': 0,
          'spent': false,
          'value': 4999995000,
          'spending_outpoints': [],
          'n': 0,
          'tx_index': 1,
          'script': '76a91488ac',
          'addr': '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
        }
      ],
    }
  ],
};

final testLatestBlockResponse = {
  'hash': '0000000000000000000b4d0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e',
  'time': 1624164176,
  'block_index': 693126,
  'height': 693126,
  'txIndexes': [123456, 234567, 345678],
};

final testTezosResponse = [
  {
    'cycle': -1,
    'level': 0,
    'hash': 'BLockGenesisGenesisGenesisGenesisGenesisf79b5d1CoW2',
    'timestamp': '2018-06-30T16:07:32Z',
    'proto': -1,
    'payloadRound': 0,
    'blockRound': 0,
    'validations': 0,
    'deposit': 0,
    'rewardLiquid': 0,
    'rewardStakedOwn': 0,
    'rewardStakedShared': 0,
    'bonusLiquid': 0,
    'bonusStakedOwn': 0,
    'bonusStakedShared': 0,
    'fees': 0,
    'nonceRevealed': false,
    'lbToggleEma': 0,
    'aiToggleEma': 0,
    'reward': 0,
    'bonus': 0,
    'priority': 0,
    'lbEscapeVote': false,
    'lbEscapeEma': 0,
  },
  {
    'cycle': 0,
    'level': 1,
    'hash': 'BLSqrcLvFtqVCx8WSqkVJypW2kAVRM3eEj2BHgBsB6kb24NqYev',
    'timestamp': '2018-06-30T17:39:57Z',
    'proto': 0,
    'payloadRound': 0,
    'blockRound': 0,
    'validations': 0,
    'deposit': 0,
    'rewardLiquid': 0,
    'rewardStakedOwn': 0,
    'rewardStakedShared': 0,
    'bonusLiquid': 0,
    'bonusStakedOwn': 0,
    'bonusStakedShared': 0,
    'fees': 0,
    'nonceRevealed': false,
    'lbToggleEma': 0,
    'aiToggleEma': 0,
    'reward': 0,
    'bonus': 0,
    'priority': 0,
    'lbEscapeVote': false,
    'lbEscapeEma': 0,
  },
  {
    'cycle': 0,
    'level': 2,
    'hash': 'BMMmnb2LoJQs3PjvhysXAgK2pAjJE71hoqXFCs6u85xUH3KrRqa',
    'timestamp': '2018-06-30T17:40:57Z',
    'proto': 1,
    'payloadRound': 0,
    'blockRound': 0,
    'validations': 0,
    'deposit': 0,
    'rewardLiquid': 0,
    'rewardStakedOwn': 0,
    'rewardStakedShared': 0,
    'bonusLiquid': 0,
    'bonusStakedOwn': 0,
    'bonusStakedShared': 0,
    'fees': 0,
    'nonceRevealed': false,
    'proposer': {
      'alias': 'Foundation baker 3 legacy',
      'address': 'tz3RB4aoyjov4KEVRbuhvQ1CKJgBJMWhaeB8',
    },
    'producer': {
      'alias': 'Foundation baker 3 legacy',
      'address': 'tz3RB4aoyjov4KEVRbuhvQ1CKJgBJMWhaeB8',
    },
    'lbToggleEma': 0,
    'aiToggleEma': 0,
    'reward': 0,
    'bonus': 0,
    'priority': 0,
    'baker': {
      'alias': 'Foundation baker 3 legacy',
      'address': 'tz3RB4aoyjov4KEVRbuhvQ1CKJgBJMWhaeB8',
    },
    'lbEscapeVote': false,
    'lbEscapeEma': 0,
  },
  {
    'cycle': 0,
    'level': 3,
    'hash': 'BMW8SnJ57KMcmSVimBhPhNP1YPYSGEJARoNRg3tdW1YScCMfBh6',
    'timestamp': '2018-06-30T17:44:27Z',
    'proto': 1,
    'payloadRound': 2,
    'blockRound': 2,
    'validations': 0,
    'deposit': 0,
    'rewardLiquid': 0,
    'rewardStakedOwn': 0,
    'rewardStakedShared': 0,
    'bonusLiquid': 0,
    'bonusStakedOwn': 0,
    'bonusStakedShared': 0,
    'fees': 0,
    'nonceRevealed': false,
    'proposer': {
      'alias': 'Foundation Baker 1 legacy',
      'address': 'tz3RDC3Jdn4j15J7bBHZd29EUee9gVB1CxD9',
    },
    'producer': {
      'alias': 'Foundation Baker 1 legacy',
      'address': 'tz3RDC3Jdn4j15J7bBHZd29EUee9gVB1CxD9',
    },
    'lbToggleEma': 0,
    'aiToggleEma': 0,
    'reward': 0,
    'bonus': 0,
    'priority': 2,
    'baker': {
      'alias': 'Foundation Baker 1 legacy',
      'address': 'tz3RDC3Jdn4j15J7bBHZd29EUee9gVB1CxD9',
    },
    'lbEscapeVote': false,
    'lbEscapeEma': 0,
  },
  {
    'cycle': 0,
    'level': 4,
    'hash': 'BLLcTCR2UhC8eoUK5gzqJp3KsPLDNKruSFdskdvsMgSY48wFgX3',
    'timestamp': '2018-06-30T17:45:27Z',
    'proto': 1,
    'payloadRound': 0,
    'blockRound': 0,
    'validations': 32,
    'deposit': 0,
    'rewardLiquid': 0,
    'rewardStakedOwn': 0,
    'rewardStakedShared': 0,
    'bonusLiquid': 0,
    'bonusStakedOwn': 0,
    'bonusStakedShared': 0,
    'fees': 0,
    'nonceRevealed': false,
    'proposer': {
      'alias': 'Foundation baker 6 legacy',
      'address': 'tz3UoffC7FG7zfpmvmjUmUeAaHvzdcUvAj6r',
    },
    'producer': {
      'alias': 'Foundation baker 6 legacy',
      'address': 'tz3UoffC7FG7zfpmvmjUmUeAaHvzdcUvAj6r',
    },
    'lbToggleEma': 0,
    'aiToggleEma': 0,
    'reward': 0,
    'bonus': 0,
    'priority': 0,
    'baker': {
      'alias': 'Foundation baker 6 legacy',
      'address': 'tz3UoffC7FG7zfpmvmjUmUeAaHvzdcUvAj6r',
    },
    'lbEscapeVote': false,
    'lbEscapeEma': 0,
  },
  {
    'cycle': 0,
    'level': 5,
    'hash': 'BM2SfYjRiJ5EMd4Zv8C7ni1W6TnYh39f5cakgCavSjmjnwSFaSk',
    'timestamp': '2018-06-30T17:46:27Z',
    'proto': 1,
    'payloadRound': 0,
    'blockRound': 0,
    'validations': 32,
    'deposit': 0,
    'rewardLiquid': 0,
    'rewardStakedOwn': 0,
    'rewardStakedShared': 0,
    'bonusLiquid': 0,
    'bonusStakedOwn': 0,
    'bonusStakedShared': 0,
    'fees': 0,
    'nonceRevealed': false,
    'proposer': {
      'alias': 'Foundation baker 7 legacy',
      'address': 'tz3WMqdzXqRWXwyvj5Hp2H7QEepaUuS7vd9K',
    },
    'producer': {
      'alias': 'Foundation baker 7 legacy',
      'address': 'tz3WMqdzXqRWXwyvj5Hp2H7QEepaUuS7vd9K',
    },
    'lbToggleEma': 0,
    'aiToggleEma': 0,
    'reward': 0,
    'bonus': 0,
    'priority': 0,
    'baker': {
      'alias': 'Foundation baker 7 legacy',
      'address': 'tz3WMqdzXqRWXwyvj5Hp2H7QEepaUuS7vd9K',
    },
    'lbEscapeVote': false,
    'lbEscapeEma': 0,
  },
  {
    'cycle': 0,
    'level': 6,
    'hash': 'BL2mzgAmb8XFza15bW15tPE6KDnU4nc4B5PYP4G15EvSTQJ8ffT',
    'timestamp': '2018-06-30T17:47:27Z',
    'proto': 1,
    'payloadRound': 0,
    'blockRound': 0,
    'validations': 32,
    'deposit': 0,
    'rewardLiquid': 0,
    'rewardStakedOwn': 0,
    'rewardStakedShared': 0,
    'bonusLiquid': 0,
    'bonusStakedOwn': 0,
    'bonusStakedShared': 0,
    'fees': 0,
    'nonceRevealed': false,
    'proposer': {
      'alias': 'Foundation baker 7 legacy',
      'address': 'tz3WMqdzXqRWXwyvj5Hp2H7QEepaUuS7vd9K',
    },
    'producer': {
      'alias': 'Foundation baker 7 legacy',
      'address': 'tz3WMqdzXqRWXwyvj5Hp2H7QEepaUuS7vd9K',
    },
    'lbToggleEma': 0,
    'aiToggleEma': 0,
    'reward': 0,
    'bonus': 0,
    'priority': 0,
    'baker': {
      'alias': 'Foundation baker 7 legacy',
      'address': 'tz3WMqdzXqRWXwyvj5Hp2H7QEepaUuS7vd9K',
    },
    'lbEscapeVote': false,
    'lbEscapeEma': 0,
  },
  {
    'cycle': 0,
    'level': 7,
    'hash': 'BLFbq1crBoTWRa6vLSKYui5kd4TBsbDHE4Qz8DJ5EayYCiJHKu2',
    'timestamp': '2018-06-30T17:48:27Z',
    'proto': 1,
    'payloadRound': 0,
    'blockRound': 0,
    'validations': 32,
    'deposit': 0,
    'rewardLiquid': 0,
    'rewardStakedOwn': 0,
    'rewardStakedShared': 0,
    'bonusLiquid': 0,
    'bonusStakedOwn': 0,
    'bonusStakedShared': 0,
    'fees': 0,
    'nonceRevealed': false,
    'proposer': {
      'alias': 'Foundation baker 7 legacy',
      'address': 'tz3WMqdzXqRWXwyvj5Hp2H7QEepaUuS7vd9K',
    },
    'producer': {
      'alias': 'Foundation baker 7 legacy',
      'address': 'tz3WMqdzXqRWXwyvj5Hp2H7QEepaUuS7vd9K',
    },
    'lbToggleEma': 0,
    'aiToggleEma': 0,
    'reward': 0,
    'bonus': 0,
    'priority': 0,
    'baker': {
      'alias': 'Foundation baker 7 legacy',
      'address': 'tz3WMqdzXqRWXwyvj5Hp2H7QEepaUuS7vd9K',
    },
    'lbEscapeVote': false,
    'lbEscapeEma': 0,
  },
  {
    'cycle': 0,
    'level': 8,
    'hash': 'BMcLeMTu3bsMuBL2W1yHNCkM2tqnmeN72RbxvZxEHbK83mggqpE',
    'timestamp': '2018-06-30T17:49:27Z',
    'proto': 1,
    'payloadRound': 0,
    'blockRound': 0,
    'validations': 32,
    'deposit': 0,
    'rewardLiquid': 0,
    'rewardStakedOwn': 0,
    'rewardStakedShared': 0,
    'bonusLiquid': 0,
    'bonusStakedOwn': 0,
    'bonusStakedShared': 0,
    'fees': 0,
    'nonceRevealed': false,
    'proposer': {
      'alias': 'Foundation baker 5 legacy',
      'address': 'tz3NExpXn9aPNZPorRE4SdjJ2RGrfbJgMAaV',
    },
    'producer': {
      'alias': 'Foundation baker 5 legacy',
      'address': 'tz3NExpXn9aPNZPorRE4SdjJ2RGrfbJgMAaV',
    },
    'lbToggleEma': 0,
    'aiToggleEma': 0,
    'reward': 0,
    'bonus': 0,
    'priority': 0,
    'baker': {
      'alias': 'Foundation baker 5 legacy',
      'address': 'tz3NExpXn9aPNZPorRE4SdjJ2RGrfbJgMAaV',
    },
    'lbEscapeVote': false,
    'lbEscapeEma': 0,
  },
  {
    'cycle': 0,
    'level': 9,
    'hash': 'BLuFnCYme4GPmeRJAuJ4eA6BuSNo3AzcBfoDnSvfANJUPqFx9Mk',
    'timestamp': '2018-06-30T17:50:27Z',
    'proto': 1,
    'payloadRound': 0,
    'blockRound': 0,
    'validations': 32,
    'deposit': 0,
    'rewardLiquid': 0,
    'rewardStakedOwn': 0,
    'rewardStakedShared': 0,
    'bonusLiquid': 0,
    'bonusStakedOwn': 0,
    'bonusStakedShared': 0,
    'fees': 0,
    'nonceRevealed': false,
    'proposer': {
      'alias': 'Foundation baker 3 legacy',
      'address': 'tz3RB4aoyjov4KEVRbuhvQ1CKJgBJMWhaeB8',
    },
    'producer': {
      'alias': 'Foundation baker 3 legacy',
      'address': 'tz3RB4aoyjov4KEVRbuhvQ1CKJgBJMWhaeB8',
    },
    'lbToggleEma': 0,
    'aiToggleEma': 0,
    'reward': 0,
    'bonus': 0,
    'priority': 0,
    'baker': {
      'alias': 'Foundation baker 3 legacy',
      'address': 'tz3RB4aoyjov4KEVRbuhvQ1CKJgBJMWhaeB8',
    },
    'lbEscapeVote': false,
    'lbEscapeEma': 0,
  },
  {
    'cycle': 0,
    'level': 10,
    'hash': 'BLq3jarZuxz4F7pamd9xvNmrSstMqAS2JMP5SB2VMqpdWpN88eJ',
    'timestamp': '2018-06-30T17:51:27Z',
    'proto': 1,
    'payloadRound': 0,
    'blockRound': 0,
    'validations': 32,
    'deposit': 0,
    'rewardLiquid': 0,
    'rewardStakedOwn': 0,
    'rewardStakedShared': 0,
    'bonusLiquid': 0,
    'bonusStakedOwn': 0,
    'bonusStakedShared': 0,
    'fees': 0,
    'nonceRevealed': false,
    'proposer': {
      'alias': 'Foundation baker 8 legacy',
      'address': 'tz3VEZ4k6a4Wx42iyev6i2aVAptTRLEAivNN',
    },
    'producer': {
      'alias': 'Foundation baker 8 legacy',
      'address': 'tz3VEZ4k6a4Wx42iyev6i2aVAptTRLEAivNN',
    },
    'lbToggleEma': 0,
    'aiToggleEma': 0,
    'reward': 0,
    'bonus': 0,
    'priority': 0,
    'baker': {
      'alias': 'Foundation baker 8 legacy',
      'address': 'tz3VEZ4k6a4Wx42iyev6i2aVAptTRLEAivNN',
    },
    'lbEscapeVote': false,
    'lbEscapeEma': 0,
  },
  {
    'cycle': 0,
    'level': 11,
    'hash': 'BM9TYubKzs9hciq85fBKJpjG9Ufk9e3WabvFpk5TzUwvHA1Uk2u',
    'timestamp': '2018-06-30T17:52:27Z',
    'proto': 1,
    'payloadRound': 0,
    'blockRound': 0,
    'validations': 32,
    'deposit': 0,
    'rewardLiquid': 0,
    'rewardStakedOwn': 0,
    'rewardStakedShared': 0,
    'bonusLiquid': 0,
    'bonusStakedOwn': 0,
    'bonusStakedShared': 0,
    'fees': 0,
    'nonceRevealed': false,
    'proposer': {
      'alias': 'Foundation baker 5 legacy',
      'address': 'tz3NExpXn9aPNZPorRE4SdjJ2RGrfbJgMAaV',
    },
    'producer': {
      'alias': 'Foundation baker 5 legacy',
      'address': 'tz3NExpXn9aPNZPorRE4SdjJ2RGrfbJgMAaV',
    },
    'lbToggleEma': 0,
    'aiToggleEma': 0,
    'reward': 0,
    'bonus': 0,
    'priority': 0,
    'baker': {
      'alias': 'Foundation baker 5 legacy',
      'address': 'tz3NExpXn9aPNZPorRE4SdjJ2RGrfbJgMAaV',
    },
    'lbEscapeVote': false,
    'lbEscapeEma': 0,
  },
];
