name: blockchain_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.1.3
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  http_interceptor: ^2.0.0-beta.8
  injectable: ^2.4.1
  intl: ^0.19.0
  logger: ^2.3.0
  once: ^1.6.3
  path: ^1.9.0
  path_provider: ^2.0.15
  toastification: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: 
  hive_generator:
  hive_test: ^1.0.1
  injectable_generator:
  # isar_generator: 
  json_serializable: 
  
  mockito: ^5.4.4
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
